from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from moon_media_lab.errors import InvalidArguments
from moon_media_lab.jobs import write_json
from moon_media_lab.knowledge.bundle import build_knowledge_bundle


WIKI_FILES = [
    "transcript.clean.md",
    "transcript.speakers.md",
    "transcript.en.clean.md",
    "transcript.bilingual.md",
    "knowledge.md",
    "knowledge.structured.json",
    "recommendations.md",
    "english-study.md",
]


def export_wiki_bundle(job_dir: Path, output_dir: Path) -> Path:
    """Export portable Markdown + JSON without binding to a Wiki vendor."""
    job_dir = job_dir.expanduser().resolve()
    manifest_path = build_knowledge_bundle(job_dir)
    output_dir = output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    copied: list[str] = []
    for name in WIKI_FILES:
        source = job_dir / name
        if source.is_file():
            shutil.copy2(source, output_dir / name)
            copied.append(name)
    shutil.copy2(manifest_path, output_dir / manifest_path.name)

    structured = _read_json(job_dir / "knowledge.structured.json")
    portable = {
        "schemaVersion": "0.1.0",
        "id": f"wiki:{job_dir.name}",
        "title": _title(job_dir),
        "sourceJob": job_dir.name,
        "exportedAt": datetime.now(timezone.utc).isoformat(),
        "files": copied,
        "knowledge": structured,
    }
    write_json(output_dir / "knowledge.json", portable)
    (output_dir / "index.md").write_text(_index(portable), encoding="utf-8")
    return output_dir


def _title(job_dir: Path) -> str:
    knowledge = job_dir / "knowledge.md"
    if knowledge.is_file():
        for line in knowledge.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return job_dir.name


def _read_json(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise InvalidArguments(f"Invalid structured knowledge JSON: {path}") from exc
    return payload if isinstance(payload, dict) else {}


def _index(payload: dict[str, Any]) -> str:
    lines = [
        "---",
        f"id: {payload['id']}",
        f"title: {json.dumps(payload['title'], ensure_ascii=False)}",
        f"source_job: {payload['sourceJob']}",
        "status: candidate",
        "rights: private",
        "---",
        "",
        f"# {payload['title']}",
        "",
        "> Portable Wiki export generated by moon-media-lab. Review facts and rights before publishing.",
        "",
        "## Assets",
        "",
    ]
    lines.extend(f"- [{name}]({name})" for name in payload["files"])
    return "\n".join(lines) + "\n"

